// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD21KZZV_r_Jilhua0LU8cWjHKH9NbqGSQ',
    appId: '1:735105502354:web:4ebc136215705164052a4b',
    messagingSenderId: '735105502354',
    projectId: 'flutter-firebase-auth-c79e7',
    authDomain: 'flutter-firebase-auth-c79e7.firebaseapp.com',
    storageBucket: 'flutter-firebase-auth-c79e7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbdSYjllXQIHp3OQ3aYpJVKfLkeqP89h0',
    appId: '1:735105502354:android:f42e84131471c7fd052a4b',
    messagingSenderId: '735105502354',
    projectId: 'flutter-firebase-auth-c79e7',
    storageBucket: 'flutter-firebase-auth-c79e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkS43vDb6Xt_etDv8O8gj5qBiLr_LxZTE',
    appId: '1:735105502354:ios:7bdf5d23d076f919052a4b',
    messagingSenderId: '735105502354',
    projectId: 'flutter-firebase-auth-c79e7',
    storageBucket: 'flutter-firebase-auth-c79e7.appspot.com',
    iosClientId: '735105502354-mgl77mq3lbfia5efbhq9bovfafvchcsi.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseAuth',
  );
}
